# Generated by Django 2.1.3 on 2019-01-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0002_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
