# Generated by Django 2.1.3 on 2019-01-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0003_auto_20190107_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('RPG', 'role playing games'), ('racing', 'racing games'), ('action', 'action games'), ('strategy', 'strategy games'), ('shooter', 'shooter games'), ('survival', 'survival games'), ('horror', 'horror games'), ('other', 'other games')], max_length=1),
        ),
    ]
