# Generated by Django 2.1.3 on 2019-01-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0004_auto_20190107_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('rpg', 'role playing'), ('rac', 'racing'), ('act', 'action'), ('str', 'strategy'), ('sho', 'shooter'), ('sur', 'survival'), ('hor', 'horror'), ('oth', 'other')], max_length=1),
        ),
    ]
