# Generated by Django 2.1.3 on 2019-01-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0005_auto_20190107_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
