# Generated by Django 2.1.3 on 2019-01-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0006_delete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('rpg', 'role playing'), ('rac', 'racing'), ('act', 'action'), ('str', 'strategy'), ('sho', 'shooter'), ('sur', 'survival'), ('hor', 'horror'), ('oth', 'other')], max_length=3),
        ),
    ]
