# Generated by Django 2.1.3 on 2019-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0007_auto_20190107_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='highscores',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='juguser',
            name='games',
            field=models.ManyToManyField(to='jstore.Game'),
        ),
    ]
