# Generated by Django 2.1.3 on 2019-01-10 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0008_auto_20190109_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameid',
            field=models.PositiveIntegerField(default=10000, unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AddField(
            model_name='game',
            name='gameurl',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
