# Generated by Django 2.1.3 on 2019-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0011_auto_20190123_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesave',
            name='gamestate',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
