# Generated by Django 2.1.3 on 2019-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0014_auto_20190123_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='highscores',
            field=models.TextField(default=[], max_length=100),
        ),
    ]
