# Generated by Django 2.1.3 on 2019-01-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0015_auto_20190123_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='highscores',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
