# Generated by Django 2.1.3 on 2019-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstore', '0016_auto_20190124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='highscores',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
